create or replace TRIGGER SUPERVISIONES_TGR 
AFTER 
    UPDATE 
    ON SUPERVISIONES 
    FOR EACH ROW
DECLARE 
    C_TABLA CONSTANT VARCHAR2(30):= 'SUPERVISIONES';
    V_DESCRIPCION VARCHAR2(2000) := 'Sin comentarios';
BEGIN
        V_DESCRIPCION:= C_TABLA||'{ '
        || :OLD.OBSERVASIONES||' : '||:NEW.OBSERVASIONES ||', '
        || :OLD.OBJETIVO||' : '||:NEW.OBJETIVO ||', ' 
        || :OLD.FECHA||' : '||:NEW.FECHA ||', '
        || :OLD.HORA_INICIO||' : '||:NEW.HORA_INICIO ||', '
        || :OLD.HORA_FIN||' : '||:NEW.HORA_FIN ||' }';         
    
    INSERT INTO BITACORA_SUPERVISION
     VALUES(SEQ_BITACORA_SUPERV.nextval, V_DESCRIPCION, SYSDATE, USER);
END;


INSERT INTO DEPARTAMENTOS VALUES (1,'AAAA', 'Contabilidad');
INSERT INTO DEPARTAMENTOS VALUES (2,'AAAA', 'Recursos Humanos');
INSERT INTO DEPARTAMENTOS VALUES (3,'AAAA', 'Marketing');

INSERT INTO TIPO_COORDINADORES VALUES (1,'HOLA', 'Coordinador Profesional');
INSERT INTO TIPO_COORDINADORES VALUES (2,'HOLA', 'Coordinador Tecnico');